apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::737641393003:role/clo835-service-account-role
automountServiceAccountToken: false

# Run the scripts/serviceaccount-iam-role.sh script before deploying this manifest